### ISSUE TITLE
Clarify licensing?

### ISSUE THREAD

**Issue by anp** [tokio-rs/tokio-trace-nursery#48]
Hi! I can't find any licensing information in the repository so far. Are you planning to license these crates under an MIT license, as tokio itself has? If so, it'd be awesome if one were added ASAP with the sign-off of existing contributors so that new contributions are appropriately licensed.

**Comment by hawkw** [comment]
Thanks for pointing that out --- the intention is to license these crates under the same license as the rest of `tokio`. This repo was originally created as a clone of the prototype repo, so I forgot to add a license (and a README), my bad.

**Comment by hawkw** [comment]
@davidbarsky, @LucioFranco, @kanishkarj, @kleimkuhler, and @jxs, you've all committed code to this repository. I'm guessing you're all comfortable licensing your contributions under the same license as the rest of tokio, but I want to double check to make sure.

**Comment by LucioFranco** [comment]
👍 from me

**Comment by jxs** [comment]
yes ofc 🙂

**Comment by davidbarsky** [comment]
@hawkw I'm okay with that!

**Comment by kleimkuhler** [comment]
@hawkw Yes I am okay with that as well!

**Comment by hawkw** [comment]
Great I figured as much --- just wanted to make sure for "legal reasons" :)

**Comment by anp** [comment]
Yay! I’d open a PR to add the license file but I’m not sure whether my employment agreement allows it (I’m normally restricted from contributing to repos which have approved licenses, kinda hilarious bigco chicken and egg situation). Any chance one of y’all have a sec to throw one up? I have a couple of things I’d love to contribute :D.

**Comment by hawkw** [comment]
Done! https://github.com/tokio-rs/tokio-trace-nursery/commit/3be08a81939384af033ce275771f3eec17e6f120
