### ISSUE TITLE
Reloading an EnvFilter in tokio-trace-fmt

### ISSUE THREAD

**Issue by amousset** [tokio-rs/tokio-trace-nursery#63]
I'm trying to use the filter reloading introduced in #45, but get stuck with `cannot infer type for N`, for example with:

```rust
let subscriber = FmtSubscriber::builder().with_filter_reloading().full().finish();
let reload_handle = subscriber.reload_handle();
reload_handle.reload(EnvFilter::from_default_env())
```
which gives:

```
|                     match reload_handle.reload(EnvFilter::from_default_env()) {
|                                         ^^^^^^ cannot infer type for `N`
```

(But N cannot be specified because of `impl Into`)
Am I missing something?

**Comment by hawkw** [comment]
Does 
```rust
reload_handle.reload::<default::NewRecorder>(...);
``` 
work?

I think it may be worth looking at changing the type signature for `EnvFilter` to make this a little less confusing. The filter interface (like most of the other crates in the `tokio-trace-nursery` repo) is still in a prototype state. I can look into improving this API.

**Comment by hawkw** [comment]
A quick update: I've opened #64, which should fix this. I've included your sample code as a test in that branch, and it now compiles. Thanks for reporting this!

**Comment by amousset** [comment]
I successfully tested #64, thanks for the fix! (and thanks a lot for tokio-trace!)

**Comment by hawkw** [comment]
@amousset my pleasure, glad it was easy to fix. Thanks again for the bug report. #64 is now on master!
